name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        env: 
            NODE_ENV: production
            PORT: 8081
            HOST: localhost
            CORS_ORIGIN: "*"
            COMMON_RATE_LIMIT_WINDOW_MS: "1000" # Window size for rate limiting (ms)
            COMMON_RATE_LIMIT_MAX_REQUESTS: "20" # Max number of requests per window per IP
            MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run build