name: Code Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        env: 
          NODE_ENV: production
          PORT: 8081
          HOST: localhost
          CORS_ORIGIN: "*"
          COMMON_RATE_LIMIT_WINDOW_MS: "1000" # Window size for rate limiting (ms)
          COMMON_RATE_LIMIT_MAX_REQUESTS: "20" # Max number of requests per window per IP
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: biome ci .